flowchart TD
    A[OODA] --> B{Is it sunny?}
    B -->|Yes| C[Go for a walk]
    B -->|No| D[Read a book]
    B -->|No| E[Be like Goggins & go for a walk anyways]
    C --> F[Enjoy the day]
    D --> F[Enjoy the day]
    E --> F[Enjoy the day]